[package]
name = "solrunners-site"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
lazy_static = "1.5.0"
rocket = "0.5.1"
tera = "1.20.0"

[lints.clippy]
perf = "warn"
complexity = "warn"
correctness = "warn"
suspicious = "warn"
style = "warn"