name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: ci-build
        path: ./target
        retention-days: 1
        overwrite: true
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ci-build
          path: ./target          
      - name: Test
        run: cargo test --verbose
    
  
 
